apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: blackbox-exporter
    app.kubernetes.io/version: v0.18.0
  name: blackbox-exporter
  namespace: monitoring
spec:
  ports:
  - name: https
    port: 9115
    targetPort: https
  - name: probe
    port: 19115
    targetPort: http
  selector:
    app.kubernetes.io/name: blackbox-exporter
